displayName=Poison Dynamite
author=niks
description=Hit chance calculator and countdown timer for Dynamite(p)
tags=poison,dynamite,timer,skiller,combat
plugins=com.runelite.poisondynamite.PoisonDynamitePlugin
